[mysqldb]
user = "root"
host = "localhost"
port = 3306
password = "Ash@95kh"
database = "starwarsdb2"

[swapi]
home_url = "https://swapi.dev"
vehicle = "/api/vehicles"
starship = "/api/starships"
character = "/api/people"
species = "/api/species"
film = "/api/film"